version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    command: --ISCAgent false
    ports: 
      - 32782:1972
      - 32783:52773
      - 32784:53773
    volumes:
      - ./:/irisdev/app
      - ./share:/usr/irissys/csp/user/fhirUI/share
